Add support for persistent-2.14 to serversession-backend-persistent
yesodweb/serversession pull request #39
Opened 2024-08-20 15:51 UTC by belevy

Fixes #38 

Bumped version to 2.0.2

2024-08-23 08:08 UTC, ncaq commented
Is `toPersistValues` on line 121 a typo for `toPersistFields`?

2024-08-23 08:23 UTC, ncaq requested changes

2024-08-23 08:23 UTC, ncaq commented on serversession-backend-persistent/src/Web/ServerSession/Backend/Persistent/Internal/Impl.hs
> +  toPersistValues (PersistentSession a b c d e) =
Is `toPersistValues` a typo for `toPersistFields`?

2024-08-23 12:14 UTC, belevy commented on serversession-backend-persistent/src/Web/ServerSession/Backend/Persistent/Internal/Impl.hs
> +  toPersistValues (PersistentSession a b c d e) =
Indeed I appear to have been a bit aggressive in my renaming

2024-08-24 06:27 UTC, ncaq approved these changes

2024-08-24 06:28 UTC, merged

2024-08-24 06:31 UTC, ncaq commented
Thank you.
I uploaded.